## 基础配置
style_image: img/wave.jpg # 指定原始的风格图像
naming: "wave" # 模型的名字，决定了checkpoint和events文件的保存文件夹
model_path: models  # checkpoint和events文件保存的根目录。最后所有的checkpoint和events文件都保存在 <model_path>/<naming>

## 各个损失的权重
content_weight: 1.0  # 内容损失的权重
style_weight: 220.0  # 风格损失的权重
tv_weight: 0.0  # weight for total variation loss

## The size, the iter number to run
image_size: 256
batch_size: 4
epoch: 2

## 损失网络
loss_model: "vgg_16"
content_layers:  # use these layers for content loss
  - "vgg_16/conv3/conv3_3"
style_layers:  # use these layers for style loss
  - "vgg_16/conv1/conv1_2"
  - "vgg_16/conv2/conv2_2"
  - "vgg_16/conv3/conv3_3"
  - "vgg_16/conv4/conv4_3"
checkpoint_exclude_scopes: "vgg_16/fc"  # 只用到卷积层，不需要fc层
loss_model_file: "pretrained/vgg_16.ckpt"  # the path to the 预训练模型
